"""Sample data for trying the app (36 fictional songs).

Titles are generic liturgical phrases, composers are fictional and the opening
lines are invented; no copyrighted lyrics are used. Load with `thanhca seed`.
"""

from __future__ import annotations

from datetime import timedelta

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from .models import Category, Song, utcnow

# (code, binder, page, song number, title, composer, first sentence, notes, added days ago, updated days ago)
SAMPLE_SONGS: list[tuple[str, int, int, int, str, str | None, str, str | None, int, int]] = [
    # Nhập lễ (1 binder)
    (
        "NL",
        1,
        1,
        101,
        "Con Hân Hoan Tiến Vào",
        "Nguyễn Văn An",
        "Con hân hoan tiến vào nhà Chúa, lòng rộn ràng câu hát tri ân",
        None,
        210,
        40,
    ),
    (
        "NL",
        1,
        2,
        102,
        "Hãy Đến Đây Ca Mừng",
        "Trần Minh Đức",
        "Hãy đến đây ta cùng nhau ca mừng Thiên Chúa, Đấng dựng nên trời đất",
        None,
        205,
        205,
    ),
    (
        "NL",
        1,
        3,
        12,
        "Muôn Dân Ơi Hãy Vui Lên",
        "Lm. Phạm Quang Huy",
        "Muôn dân ơi hãy vui lên, vỗ tay reo mừng danh Chúa",
        "Bản 4 bè (SATB).",
        200,
        15,
    ),
    (
        "NL",
        1,
        10,
        120,
        "Bước Vào Đền Thánh",
        "Lê Thị Hồng Nhung",
        "Bước vào đền thánh hôm nay, lòng con thao thức một niềm tin yêu",
        None,
        150,
        150,
    ),
    (
        "NL",
        1,
        11,
        103,
        "Tiếng Chuông Gọi Mời",
        "Nguyễn Văn An",
        "Tiếng chuông ngân vang gọi mời đoàn con về chung lời ca",
        None,
        90,
        90,
    ),
    # Đáp ca (5 binders)
    (
        "ĐC",
        1,
        1,
        201,
        "Chúa Là Mục Tử",
        "Lm. Phạm Quang Huy",
        "Chúa là mục tử chăn dắt tôi, tôi chẳng thiếu thốn gì",
        None,
        190,
        60,
    ),
    (
        "ĐC",
        1,
        2,
        202,
        "Hồn Tôi Khao Khát Chúa",
        "Hoàng Gia Khang",
        "Như nai rừng khát khao nguồn nước, hồn tôi mong đợi Chúa",
        None,
        180,
        180,
    ),
    (
        "ĐC",
        1,
        10,
        203,
        "Hãy Tạ Ơn Chúa",
        "Đỗ Thanh Tâm",
        "Hãy tạ ơn Chúa vì Chúa nhân từ, muôn ngàn đời Chúa vẫn trung thành",
        None,
        170,
        20,
    ),
    (
        "ĐC",
        2,
        1,
        204,
        "Đất Nước Hãy Reo Mừng",
        "Vũ Đình Phúc",
        "Hỡi đất nước hãy reo mừng Thiên Chúa, hãy đàn ca tán tụng danh Người",
        None,
        160,
        160,
    ),
    (
        "ĐC",
        3,
        12,
        205,
        "Lạy Chúa Xin Đáp Lời",
        "Nguyễn Văn Bình",
        "Lạy Chúa, xin đáp lời con kêu cầu trong ngày gian khó",
        "Đáp ca Chúa nhật XXIX Thường niên.",
        140,
        7,
    ),
    (
        "ĐC",
        5,
        18,
        206,
        "Xin Thương Xót Chúng Con",
        None,
        "Xin thương xót chúng con, lạy Chúa, vì chúng con đã đắc tội",
        None,
        100,
        100,
    ),
    # Dâng lễ (2 binders)
    (
        "DL",
        1,
        1,
        301,
        "Lễ Vật Đơn Sơ",
        "Trần Minh Đức",
        "Con xin dâng lên Ngài lễ vật đơn sơ của đời con",
        None,
        185,
        185,
    ),
    (
        "DL",
        1,
        3,
        125,
        "Xin Dâng Lời Cảm Tạ",
        "Nguyễn Văn A",
        "Xin dâng lời cảm tạ hồng ân Thiên Chúa",
        "Có phần đơn ca cho giọng nữ.",
        175,
        3,
    ),
    (
        "DL",
        2,
        7,
        302,
        "Dâng Về Nhan Thánh",
        "Lê Thị Hồng Nhung",
        "Dâng về nhan thánh bánh rượu tinh tuyền, dâng cả cuộc đời con",
        None,
        95,
        45,
    ),
    # Chư Thánh (3 binders)
    (
        "CT",
        1,
        4,
        401,
        "Hiển Vinh Các Thánh",
        "Hoàng Gia Khang",
        "Hiển vinh các thánh trên trời, muôn đời ca khen Thiên Chúa",
        None,
        160,
        160,
    ),
    (
        "CT",
        3,
        2,
        402,
        "Thánh Giuse Gương Mẫu",
        "Đỗ Thanh Tâm",
        "Thánh Giuse gương mẫu âm thầm, trung tín phục vụ thánh ý Chúa",
        None,
        80,
        80,
    ),
    # Đức Mẹ (2 binders)
    (
        "MA",
        1,
        1,
        501,
        "Mẹ Ơi Xin Thương",
        "Lê Thị Hồng Nhung",
        "Mẹ ơi xin thương đoàn con lữ thứ giữa trần gian",
        None,
        230,
        12,
    ),
    (
        "MA",
        1,
        5,
        502,
        "Dâng Mẹ Đóa Hoa Hồng",
        "Nguyễn Văn An",
        "Dâng Mẹ đóa hoa hồng thắm, dâng Mẹ cả tấm lòng con",
        None,
        150,
        150,
    ),
    (
        "MA",
        2,
        3,
        503,
        "Đức Mẹ Hằng Cứu Giúp",
        "Lm. Phạm Quang Huy",
        "Lạy Đức Mẹ hằng cứu giúp, xin thương nhìn đến đoàn con",
        "Hát trong thánh lễ thứ Tư.",
        110,
        25,
    ),
    # An Táng (1 binder)
    (
        "AT",
        1,
        2,
        601,
        "Xin Cho Linh Hồn Được Nghỉ Yên",
        "Vũ Đình Phúc",
        "Xin cho linh hồn người được nghỉ yên muôn đời trong Chúa",
        None,
        140,
        140,
    ),
    # Ca Nguyện (5 binders)
    (
        "CN",
        2,
        6,
        701,
        "Lời Kinh Chiều",
        "Hoàng Gia Khang",
        "Chiều buông xuống con dâng lời kinh nguyện, xin Chúa ở lại cùng con",
        None,
        130,
        130,
    ),
    (
        "CN",
        4,
        1,
        702,
        "Bình An Của Chúa",
        "Trần Minh Đức",
        "Bình an của Chúa xin ở lại cùng con suốt đời",
        None,
        60,
        60,
    ),
    # Dân Tộc (2 binders)
    (
        "DT",
        1,
        3,
        801,
        "Kính Nhớ Tổ Tiên",
        "Nguyễn Văn Bình",
        "Ngày đầu năm mới con dâng lời tri ân tổ tiên ông bà",
        "Dùng trong Thánh lễ Mùng Hai Tết.",
        70,
        70,
    ),
    # Giáng Sinh (4 binders)
    (
        "GS",
        1,
        1,
        901,
        "Đêm Đông Giá Lạnh",
        "Đỗ Thanh Tâm",
        "Đêm đông giá lạnh, trời cao sao sáng soi đường",
        None,
        300,
        50,
    ),
    (
        "GS",
        2,
        8,
        902,
        "Hang Bêlem Ánh Sao",
        "Lê Thị Hồng Nhung",
        "Hang Bêlem ánh sao đêm ấy, Chúa Hài Đồng giáng sinh",
        None,
        290,
        290,
    ),
    (
        "GS",
        4,
        22,
        903,
        "Mừng Chúa Giáng Trần",
        "Vũ Đình Phúc",
        "Mừng Chúa giáng trần, muôn dân vui ca hát",
        None,
        280,
        9,
    ),
    # Hôn Phối (1 binder)
    (
        "HP",
        1,
        1,
        1001,
        "Tình Yêu Trong Chúa",
        "Trần Minh Đức",
        "Hôm nay hai con về đây xin Chúa chúc lành cho tình yêu",
        None,
        120,
        120,
    ),
    # Kính Chúa (2 binders)
    (
        "KC",
        1,
        9,
        1101,
        "Ngợi Khen Thiên Chúa Tình Yêu",
        "Nguyễn Văn An",
        "Ngợi khen Thiên Chúa tình yêu, Đấng yêu thương con muôn đời",
        None,
        115,
        115,
    ),
    # Kết Lễ (1 binder)
    (
        "KL",
        1,
        1,
        1201,
        "Ra Đi Loan Báo Tin Mừng",
        "Hoàng Gia Khang",
        "Ra đi loan báo Tin Mừng, đem tình yêu Chúa đến muôn nơi",
        None,
        220,
        220,
    ),
    (
        "KL",
        1,
        2,
        1202,
        "Tạ Ơn Cuối Lễ",
        "Lm. Phạm Quang Huy",
        "Thánh lễ đã xong, con xin dâng lời tạ ơn Chúa",
        None,
        85,
        85,
    ),
    # Phục Sinh (5 binders)
    (
        "PS",
        1,
        1,
        1301,
        "Alleluia Mừng Chúa Phục Sinh",
        "Đỗ Thanh Tâm",
        "Alleluia, mừng Chúa phục sinh khải hoàn vinh quang",
        None,
        60,
        60,
    ),
    ("PS", 2, 7, 1302, "Chúa Đã Sống Lại", "Nguyễn Văn Bình", "Alleluia, Chúa đã sống lại thật rồi", None, 55, 5),
    (
        "PS",
        3,
        4,
        1305,
        "Vui Lên Hỡi Trần Gian",
        "Hoàng Gia Khang",
        "Vui lên hỡi trần gian, ngôi mộ đá đã mở toang",
        None,
        52,
        52,
    ),
    (
        "PS",
        4,
        12,
        1303,
        "Ánh Sáng Phục Sinh",
        "Vũ Đình Phúc",
        "Ánh sáng phục sinh bừng lên chiếu soi trần gian",
        None,
        50,
        50,
    ),
    (
        "PS",
        5,
        9,
        1304,
        "Sáng Ngày Thứ Nhất",
        "Lê Thị Hồng Nhung",
        "Sáng ngày thứ nhất trong tuần, các bà ra thăm mồ Chúa",
        None,
        45,
        2,
    ),
    # Thánh Hiến (1 binder)
    (
        "TH",
        1,
        3,
        1401,
        "Xin Thánh Hiến Đời Con",
        "Trần Minh Đức",
        "Xin thánh hiến đời con cho tình yêu Chúa",
        None,
        30,
        1,
    ),
]


def load_sample_songs(db: Session) -> int:
    """Adds the sample songs whose location and number are still free. Safe to run twice.
    Sample data is not a real change, so it is not written to the history."""
    categories = {category.code: category for category in db.scalars(select(Category))}
    now = utcnow()
    added = 0
    for code, binder, page, number, title, composer, first_sentence, notes, added_ago, updated_ago in SAMPLE_SONGS:
        category = categories.get(code)
        if category is None or binder > category.binder_count:
            continue
        taken = db.scalar(
            select(Song.id).where(
                or_(
                    (Song.category_id == category.id) & (Song.binder_number == binder) & (Song.page_number == page),
                    Song.song_number == number,
                )
            )
        )
        if taken is not None:
            continue
        db.add(
            Song(
                category_id=category.id,
                binder_number=binder,
                page_number=page,
                song_number=number,
                title=title,
                composer=composer,
                first_sentence=first_sentence,
                notes=notes,
                created_at=now - timedelta(days=added_ago),
                updated_at=now - timedelta(days=updated_ago),
            )
        )
        added += 1
    db.commit()
    return added
